### ISSUE TITLE
Other types scan

### ISSUE THREAD

**Issue by brunoksato** [shoplinksys/react-native-scandit#2]
I'd like to know if have possible use the Type `Fast Short Range` that have in APP Scandit

https://itunes.apple.com/us/app/scandit-barcode-scanner-demo/id453880584?ls=1&mt=8

Thanks

**Comment by D1no** [comment]
Hi, yes - in the Demo-App it is simply called fancier "Fast Short Range". Indeed, that is the standard behaviour (see the documentation [here](http://docs.scandit.com/stable/ios/_s_b_s_common_8h.html#ac69df395ce731595f20b406ed99b6793).

So to scan barcodes "faster", set the scan settings `workingRange` to `"standard"`.

```js
type ScanditSettingsType = {
// (...)
  workingRange?: 'standard' | 'long';
}
```
