### ISSUE TITLE
undefined is not an object (evaluating 'reactNativeScandit2.default.setAppKey')

### ISSUE THREAD

**Issue by gregblass** [shoplinksys/react-native-scandit#5]
I'm trying to integrate the sample code into my existing app, but I keep getting:

`undefined is not an object (evaluating '_reactNativeScandit2.default.setAppKey`

I'm just doing:

    import Scandit, { ScanditPicker, ScanditSDKVersion } from 'react-native-scandit'
    import { SCANDIT_LICENSE_KEY } from '../constants'

    Scandit.setAppKey(SCANDIT_LICENSE_KEY)`

My app uses React 16 and React Native 0.50.

I am getting these warnings when I run rpm-install:

    npm WARN react-native-scandit@5.7.0-SNAPSHOT requires a peer of react@16.0.0-alpha.12 but none was installed.
    npm WARN react-native-scandit@5.7.0-SNAPSHOT requires a peer of react-native@0.47.0 but none was installed.

I'm not sure if that has anything to do with the issue, or if something still isn't linked correctly in my project.

Any ideas here?

**Comment by D1no** [comment]
Please use the official Scandit react-native bridge: https://github.com/Scandit/barcodescanner-sdk-react-native

Could be that there wars a shift in compatibility. However, please use the official version
